version: 2.1
jobs:
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install packages
          command:
            npm install

      - run:
          name: Run tests with JUnit as reporter
          command: jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

