version: 2.1
jobs:
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install jest
          command:
            npm install jest -g
      - run:
          name: Install packages
          command:
            npm install
      - run:
          name: Unit test
          command:
            node --inspect-brk node_modules/.bin/jest --runInBand
