version: 2.1
jobs:
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install packages
          command:
            npm install
      - run:
          name: Unit tests
          command:
            npm test

