version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-alpine
    steps:
      - checkout
      - run:
          name: Install packages
          command:
            npm install
      - run:
          name: "JavaScript Test Suite"
          # yarn here makes sure we are using the local jest binary
          command: yarn jest -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
            - store_test_results:
                path: reports/junit
            - store_artifacts:
                path: reports/junit

