name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: List files
      run: ls
          
    - name: Publish auth image
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: smartsoft001/auth_api
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-auth-api
 
