name: Push

# Controls when the action will run. 
on:
  push:
    branches: master

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkins.smartsoft.biz.pl"
        user: "emiljuchnikowski"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "smartsoft"
